let skill = {
		jlsg_wuwei1: "记住我军的强大吗？",
		jlsg_yansha1: "行包围之势，尽数诛之。",
		jlsg_yansha2: "兵贵神速，随我来。",
		jlsg_liuyun1: "髣髴兮若轻云之蔽月。",
		jlsg_lingbo1: "飘飖兮若流风之回雪。",
		jlsg_qingcheng1: "含辞未吐，气若幽兰。",
		jlsg_aozhan1: "哈哈哈哈哈哈哈，来送死的吧？",
		jlsg_aozhan2: "这一招如何？",
		jlsg_huxiao1: "纳命来！",
		jlsg_guicai1: "哼，我已等待多时。",
		jlsg_langgu1: "不自量力。",
		jlsg_zhuizun1: "我才是胜者，哈哈哈哈哈哈哈哈哈哈!",
		jlsg_tianshang1: "唉，只能等待奇迹。",
		jlsg_yiji1: "速战速决吧",
		jlsg_huiqu1: "且看你如何化解。",
		jlsg_jiwu1: "真是无趣，你们一起上吧。",
		jlsg_jiwu2: "谁敢挡我？",
		jlsg_sheji1: "够胆的话，就来试试？！",
		jlsg_xingyi1: "病根虽除，仍需调养百日。",
		jlsg_guagu1: "君侯身体要紧，岂能拖延？",
		jlsg_wuqin1: "流水不腐，户枢不蠹。",
		jlsg_lijian1: "夫君,你要替妾身做主啊~",
		jlsg_lijian2: "将军，那人对妾身好生无礼~",
		jlsg_manwu1: "让妾身，为您献上一舞。",
		jlsg_baiyue1: "羡慕吧",
		jlsg_yinmeng1: "君心知我心，君意共我意。",
		jlsg_xiwu1: "绝不允许你这般胡来！",
		jlsg_juelie1: "休要小看我。",
		jlsg_fangxin1: "不知您为何事烦恼？",
		jlsg_fangxin2: "您累了。",
		jlsg_xiyu1: "让您费心了。",
		jlsg_wanrou1: "我准备好了。",
		jlsg_zhouyan1: "待老夫来会会你！",
		jlsg_zhaxiang1: "肝脑涂地，无以为报！",
		jlsg_shixue1: "不经一事，不长一智。",
		jlsg_guoshi1: "小不忍，则乱大谋。",
		jlsg_guoshi2: "此事，需从长计议。",
		jlsg_yingcai1: "汝等看好了。",
		jlsg_weibao1: "一步步走向绝境吧！",
		jlsg_choulve1: "一切如我所料！",
		jlsg_jiexi1: "伙计们，一口气拿下！",
		jlsg_youxia1: "这下要再不打，可就晚了。",
		jlsg_youxia2: "给我打他个措手不及！",
		jlsg_dailao1: "散兵游勇,不攻自破。",
		jlsg_dailao2: "广施方略，以观其变。",
		jlsg_youdi1: "兵者，以诈立，以利动。",
		jlsg_ruya1: "劳谦虚己，则附之者众。",
		jlsg_quanheng1: "容我三思。",
		jlsg_xionglve1: "识大体，弃戏物，此乃君道。",
		jlsg_xionglve2: "知己长短，方能避短就长。",
		jlsg_fuzheng1: "望诸位，各司其职，各出其力。",
		jlsg_jiuzhu1: "和我一起，活着离开此地。",
		jlsg_tuwei1: "让我了结此阵。",
		jlsg_xujin1: "休想逃，乖乖受死。",
		jlsg_paoxiao1: "都站稳了，吃我一击。",
		jlsg_benxi1: "全军突击！",
		jlsg_yaozhan1: "堂堂正正的打一场吧！",
		jlsg_wenjiu1: "酒且放下，关某去去就来。",
		jlsg_wenjiu2: "关某愿取其首级，献于帐下。",
		jlsg_shuixi1: "听听这江河的咆哮吧。",
		jlsg_sanfen1: "诚如是，则汉室可兴矣。",
		jlsg_guanxing1: "知天易，逆天难。",
		jlsg_weiwo1: "挫敌锐气，静待反击之时。",
		jlsg_shouji1: "还记得我给你的锦囊吗？",
		jlsg_hemou1: "一起渡过这道难关吧！",
		jlsg_qicai1: "尽在我们掌握之中。",
		jlsg_rende1: "以德服人。",
		jlsg_chouxi1: "害我兄弟之仇，不共戴天。",
		jlsg_chouxi2: "不灭东吴，誓不归蜀。",
		jlsg_yongbing1: "拥兵安民，以固国之根本",
		jlsg_zhaoxiang1: "汝可愿降于我，为我所用？",
		jlsg_zhishi1: "需得百姓倾服，甲兵强盛。",
		jlsg_zhishi2: "用人唯才，治世依法。",
		jlsg_jianxiong1: "宁教我负天下人，休教天下人负我！",
		jlsg_zhonghou1: "放手一搏吧！",
		jlsg_ganglie1: "你能逃得掉吗？",
		jlsg_piaoling1: "夜来风雨声，花落知多少。",
		jlsg_piaoling2: "落红非无情，化泥更护君。",
		jlsg_miluo1: "灯影摇曳处，故人入梦来。",
		jlsg_miluo2: "赠君一叶春，可愿长相守？",
		jlsg_jueyan1: "国色将倾，亦要护君周全。",
		jlsg_jueyan2: "花间辞别，就此分道扬镳。",
	},
	die = {
		jlsgsr_caocao: "孤之霸业，竟有终结之时！",
		jlsgsr_daqiao: "青灯常伴，了此余生…",
		jlsgsr_diaochan: "红颜多薄命，几人能白头。",
		jlsgsr_ganning: "坏了，这下跑不了了。",
		jlsgsr_guanyu: "必将践行大义，以示后人。",
		jlsgsr_guojia: "岂能尽如人意…",
		jlsgsr_huanggai: "这条老命，已是风中之烛…",
		jlsgsr_huangyueying: "孔明大人，请您一定要赢！",
		jlsgsr_huatuo: "人可医，国难医啊。",
		jlsgsr_liubei: "云长，翼德久等了！",
		jlsgsr_luxun: "吾尚不堪大任…",
		jlsgsr_lvbu: "有意思，嗯哈哈哈哈哈哈…",
		jlsgsr_lvmeng: "大智难尽，吾已无计可施…",
		jlsgsr_machao: "可恶，绝不轻饶！",
		jlsgsr_simayi: "难道…全被识破了吗？",
		jlsgsr_sunquan: "父亲，大哥，仲谋愧矣。",
		jlsgsr_sunshangxiang: "不，我不能输…",
		jlsgsr_xiahoudun: "这仇，早晚要报！",
		jlsgsr_xiaoqiao: "花开两朵，天各一方。",
		jlsgsr_xuzhu: "我还能…接着打……",
		jlsgsr_zhangfei: "你这家伙，好生厉害",
		jlsgsr_zhangliao: "我张文远竟受此污名…",
		jlsgsr_zhaoyun: "人外有人，子龙领教了！",
		jlsgsr_zhenji: "悼良会之永绝兮，哀一逝而异乡。",
		jlsgsr_zhouyu: "谁高一筹，我心中有数。",
		jlsgsr_zhugeliang: "悠悠苍天，曷此其极。",
	};
for (let i in skill) {
	let ii = "#ext:极略/audio/skill/" + i;
	skill[ii] = skill[i];
	delete skill[i];
}
for (let i in die) {
	let ii = `#ext:极略/audio/die/${i}:die`;
	die[ii] = die[i];
	delete die[i];
}
export default { ...skill, ...die };
