import { lib, game, ui, get, ai, _status } from "../../../../noname.js";

const characterTitle = {
	jlsgsoul_caiwenji: "霜弦哀世",
	jlsgsoul_caocao: "超世英杰",
	jlsgsoul_caopi: "代汉而立",
	jlsgsoul_caoren: "樊城天堑",
	jlsgsoul_daqiao: "韶华易逝",
	jlsgsoul_dianwei: "丘峦崩摧",
	jlsgsoul_diaochan: "乱世的舞魅",
	jlsgsoul_dongzhuo: "贪欲无餍",
	jlsgsoul_ganning: "疾驱斩浪",
	jlsgsoul_guanyu: "鬼神再临",
	jlsgsoul_guojia: "天人合一",
	jlsgsoul_huanggai: "破舰炎天",
	jlsgsoul_huangyueying: "夕风霞影",
	jlsgsoul_huangzhong: "气概天参",
	jlsgsoul_huatuo: "元化重生",
	jlsgsoul_jiaxu: "冷眼下瞰",
	jlsgsoul_liubei: "烈龙之怒",
	jlsgsoul_luxun: "焚炎灭阵",
	jlsgsoul_lvbu: "修罗之道",
	jlsgsoul_lvmeng: "圣光国士",
	jlsgsoul_machao: "神威天将军",
	jlsgsoul_pangtong: "凤唳九天",
	jlsgsoul_simahui: "水镜先生",
	jlsgsoul_simayi: "晋国之祖",
	jlsgsoul_sunce: "浪起沧溟",
	jlsgsoul_sunquan: "峰林之上",
	jlsgsoul_sunshangxiang: "蕙兰巾帼",
	jlsgsoul_xiahoudun: "不灭忠侯",
	jlsgsoul_xiaoqiao: "星河共舞",
	jlsgsoul_xuzhu: "雷铸虎躯",
	jlsgsoul_zhangfei: "横扫千军",
	jlsgsoul_zhangjiao: "雷霆万钧",
	jlsgsoul_zhangliao: "威名裂胆",
	jlsgsoul_zhaoyun: "神气如龙",
	jlsgsoul_zhenji: "洛水之神",
	jlsgsoul_zhoutai: "百战不灭",
	jlsgsoul_zhouyu: "赤壁的火神",
	jlsgsoul_zhugeliang: "赤壁妖术师",
	jlsgsoul_zhurong: "绝祀之炎",

	jlsgsoul_sp_daqiao: "故梦惊澜",
	jlsgsoul_sp_diaochan: "御世之傀儡师",
	jlsgsoul_sp_ganning: "锦翎如龙",
	jlsgsoul_sp_guanyu: "青龙",
	jlsgsoul_sp_guojia: "司天",
	jlsgsoul_sp_huangyueying: "巧绝天艺",
	jlsgsoul_sp_lvbu: "罗刹天",
	jlsgsoul_sp_simayi: "鹰挚狼食",
	jlsgsoul_sp_sunshangxiang: "星流霆击",
	jlsgsoul_sp_zhangjiao: "大道无常",
	jlsgsoul_sp_zhangliao: "雁门之刑天",
	jlsgsoul_sp_zhaoyun: "破渊追天",
	jlsgsoul_sp_zhenji: "弦落九天",
	jlsgsoul_sp_zhouyu: "谈笑挽天河",
	jlsgsoul_sp_zhugeliang: "绝代智谋",
};

export default characterTitle;
